# To calculate the force in newtons of an atom bomb, we need to understand the energy released during the explosion.
# The energy released by an atomic bomb can be approximated using the formula E = mc^2, where:
# E is the energy in joules,
# m is the mass of the material undergoing fission (in kilograms),
# c is the speed of light in a vacuum (approximately 3 x 10^8 meters/second).

# For this example, let's assume a small atomic bomb releases about 15 kilotons of TNT equivalent energy.
# 1 kiloton of TNT is approximately 4.184 x 10^12 joules.
# Therefore, 15 kilotons of TNT is:
energy_released = 15 * 4.184e12  # in joules

# The force can be calculated using the formula F = E / d, where:
# F is the force in newtons,
# E is the energy in joules,
# d is the distance over which the force is applied (in meters).
# For simplicity, let's assume the distance is 1 meter.

distance = 1  # in meters
force = energy_released / distance  # in newtons

# Now we can print the calculated force
print(f"The force generated by the atomic bomb is approximately {force:.2e} newtons.")
def time_to_mars(distance_to_mars_km, speed_of_spacecraft_km_per_s):
    """
    Calculate the time it would take to get to Mars using nuclear propulsion.

    Parameters:
    distance_to_mars_km (float): The distance to Mars in kilometers.
    speed_of_spacecraft_km_per_s (float): The speed of the spacecraft in kilometers per second.

    Returns:
    float: The time in seconds it would take to reach Mars.
    """
    time_seconds = distance_to_mars_km / speed_of_spacecraft_km_per_s
    return time_seconds

# Example usage:
# Distance to Mars can vary, but an average distance is about 225 million kilometers.
# Let's assume a hypothetical speed of 10 kilometers per second for the nuclear propulsion.
distance_to_mars = 225_000_000  # in kilometers
speed_of_spacecraft = 10  # in kilometers per second

# Calculate the time to Mars
time_needed = time_to_mars(distance_to_mars, speed_of_spacecraft)
print(f"Time to reach Mars with nuclear propulsion: {time_needed / 3600:.2f} hours.")
